### ISSUE TITLE
HTOP and TOP and other packages requiring /proc do NOT work on Android 8!

### ISSUE THREAD

**Issue by Root-voidX** [sdrausty/TermuxArch#103] opened 2018-08-12 07:52 UTC
Hey everyone, so I am using a Samsung Galaxy S9+ on Android 8.0 on a SD845 soc. So I noticed that top, htop and any other app requiring /proc or /data do not work. If I run the same htop and top command in Termux it works but within arch it doesn't? This also effects makepkg as well if you wanna note that down as well.

**Comment by sdrausty** [comment] 2018-08-12 10:43
Can you post this at https://github.com/termux/proot/issues too as this is Android 8 related?

**Comment by Root-voidX** [comment] 2018-08-13 03:18
I have done so.

**Comment by sdrausty** [comment] 2018-08-13 16:32
https://bbs.archlinux.org/ this lead might help too.

**Comment by sdrausty** [comment] 2018-08-13 16:32
https://bbs.archlinux.org/ this lead might help too.

**Comment by sdrausty** [comment] 2018-08-14 00:30
@Root-voidX this commit https://github.com/sdrausty/TermuxArch/commit/9dd30dec142841db70d077d99add03f87d840898#diff-0a14072453ea02945d6a4527e38d5ca6 adds `-b proc/fake_proc_stat:/proc/stat` to TermuxArch.  Does this help the situation with htop and top on Android 8?

**Comment by Root-voidX** [comment] 2018-08-14 02:13
Hmm, @sdrausty ill try to refresh my install and check for you.

**Comment by Root-voidX** [comment] 2018-08-14 06:11
@sdrausty I tried your new commit by doing a reinstall, the system doesn't install anymore..i get a Signal Script 1 warning.

**Comment by sdrausty** [comment] 2018-08-14 13:01
@Root-voidX reinstall once again since `setupTermuxArch.sh refresh` did not work.  You probably ran into intermittent commits regarding https://github.com/termux/termux-packages/issues/2735 Termux busybox tar depreciation in favor of bsdtar.  These errors have been fixed in TermuxArch.

**Comment by sdrausty** [comment] 2018-08-14 16:43
@Root-voidX here is the lastest update https://github.com/sdrausty/TermuxArch/commit/759a8108e8f85706be1034f72f5c48ce6201855a#diff-df3f7bde82dd80e7b1136118637c557d, and it should do what fake_proc_stat should.  Does this resolve on Android 8?

**Comment by sdrausty** [comment] 2018-08-14 19:18
@Root-voidX can you post a dump of your /proc/stat `$ cat /proc/stat`?  Post from several machines, if you can.

From the tests I am performing, it appears that this should be an option, not default as at present.

**Comment by Root-voidX** [comment] 2018-08-15 04:53
Hey @sdrausty htop works for me now! top doesn't because of some tty error. So when I load htop, it shows me at least 5 distinct processes and only shows 2 cores..so I don't know how accurate that is.

**Comment by sdrausty** [comment] 2018-08-15 17:27
@Root-voidX can you check whether this change also helps with  https://github.com/sdrausty/TermuxArch/issues?q=is%3Aissue+shmem?  For example, did Firefox finally show up right in xorg?

**Comment by sdrausty** [comment] 2018-08-16 13:34
This https://github.com/sdrausty/TermuxArch/commit/25aca606bb0da8dfec3a9cd6706507eeabc0d78a commit adds the `setupTermuxArch.sh manual` option when working in the git repository and in the TermuxArchBloom directory.

**Comment by Root-voidX** [comment] 2018-08-17 02:46
@sdrausty sorry i havent been able to get the stuff done. I will try to dump those cat files for you. I havent installed xserver yet on this install, but i can definitely say that for firefox to work well, we need software mesa or hardware rendering. I belive there was a method of doing this on a rpi3 but packages are in AUR, requires makepkg to find.

**Comment by Root-voidX** [comment] 2018-08-19 08:46
@sdrausty so here is the results using cat:

[04:38 home ]$ cat /proc/stat
cat: /proc/stat: Permission denied
[04:43 home ]$ cat /proc/shmem
cat: /proc/shmem: No such file or directory

**Comment by sdrausty** [comment] 2018-08-21 20:02
Lots of changes regarding addfbinds() and addfbindprocstat() @Root-voidX:
1) Checks if stat is readable and has data.  If it's there, why fake it?
2) Detects number of processors.  Hopefully this change will make the stat bind more accurate.

Changes regrading prootstmt:
1) Adds binds from /var/binds/*.prs files while generating startbin.  

This should ease diagnostics with the PRoot statement since now there is one more method to generate it.  Enjoy!

**Comment by Root-voidX** [comment] 2018-08-22 05:58
@sdrausty I did a refresh and I keep getting this warning using startarch

`proot warning: can't sanatize binding var/fake_proc_stat: No such file or directory`

Definitely an selinux issue, unless there is a way to repress the selinux policies there isn't a away around it for me.

**Comment by sdrausty** [comment] 2018-08-27 15:51
@Root-voidX this commit https://github.com/sdrausty/TermuxArch/commit/c0d1d5b986d98578b342591e043a20433ad187b4 tweaks: 
```
if [ -n "$(ls -A "$installdir"/var/binds/*.prs)" ]; then
    for f in "$installdir"/var/binds/*.prs ; do
      . "$f"
```

The function addfbindprocstat() should add var/binds/fbindprocstat via 
addfbindprocstat8(); And the proot statement should be modified accordingly for eight CPUs.

**Comment by Root-voidX** [comment] 2018-08-28 06:40
@sdrausty 

This is what i get after i refresh:

bash setupTermuxArch.sh refresh

 🕛 > 🕛 setupTermuxArch v1.6 will refresh your TermuxArch files in /data/data/com.termux/files/home/arch.  Ensure background data is not restricted.  Run bash setupTermuxArch.sh help for additional information.  Check the wireless connection if you do not see one o'clock 🕐 below.  Checking prerequisites…

 🕛 > 🕧 Prerequisites: OK  Downloading TermuxArch…

setupTermuxArch. 100%[=======>]     153  --.-KB/s    in 0s
setupTermuxArch. 100%[=======>]  25.92K  --.-KB/s    in 0.01s

 🕛 > 🕐 TermuxArch download: OK

setupTermuxArch.sh: UPDATED
TermuxArch: RESTART setupTermuxArch.sh refresh

setupTermuxArch.sh refresh v1.6: DONE 🏁

$ bash setupTermuxArch.sh refresh

Setting mode to refresh.

 🕛 > 🕛 setupTermuxArch v1.6 id7674 will refresh your TermuxArch files in /data/data/com.termux/files/home/arch.  Ensure background data is not restricted.  Run bash setupTermuxArch.sh help for additional information.  Check the wireless connection if you do not see one o'clock 🕐 below.  Checking prerequisites…

Using wget to manage downloads.

 🕛 > 🕧 Prerequisites: OK  Downloading TermuxArch…

setupTermuxArch. 100%[=======>]     153  --.-KB/s    in 0s
setupTermuxArch. 100%[=======>]  25.92K  --.-KB/s    in 0.01s

 🕛 > 🕐 TermuxArch download: OK

 🕛 > 🕜 TermuxArch v1.6 id7674 integrity: OK
head: cannot open '/proc/stat' for reading: Permission denied
archlinuxconfig.sh: line 257: t: unbound variable
setupTermuxArch.sh refresh v1.6 id7674: (Return Value 1) DONE 🏁

$ startarch
proot warning: can't sanitize binding "var/fake_proc_stat": No such file or directory

Welcome to Arch Linux in Termux!
Install a package: pacman -S package
More  information: pacman -[D|F|Q|R|S|T|U]h
Search   packages: pacman -Ss query
Upgrade  packages: pacman -Syu

Chat: webchat.freenode.net/ #termux
Help: info query and man query
IRC:  wiki.archlinux.org/index.php/IRC_channel

[02:04 home ]$ htop
Cannot open /proc/stat: Permission denied
[02:04 home ]$

**Comment by sdrausty** [comment] 2018-08-28 08:13
The current version is v1.6 id1838" @Root-voidx The file "var/fake_proc_stat" is superseded by "var/binds/fbindprocstat" and yours should be created from [addfbindprocstat8()](https://github.com/sdrausty/TermuxArch/blob/master/archlinuxconfig.sh) which should fake 8 CPUs.

**Comment by sdrausty** [comment] 2018-08-28 16:47
> unless there is a way to repress the selinux policies there isn't a away around it 

https://github.com/michalbednarski shared quite a bit of technicalia at this https://github.com/termux/proot/issues/32#issuecomment-414053477 post.  It might be possible to resolve this https://github.com/sdrausty/termux-archlinux/issues/4 important SELinux issue as well!

**Comment by Root-voidX** [comment] 2018-08-29 06:18
@sdrausty 

Updated via git clone and retried setupTermuxArch.sh and now get this error:

$ bash TermuxArch/setupTermuxArch.sh

 🕛 > 🕛 TermuxArch v1.6 id0216 shall attempt to install Linux in /data/data/com.termux/files/home/arch.  Arch Linux in Termux PRoot shall be available upon successful completion.  To run this BASH script again, use `!!`.  Ensure background data is not restricted.  Check the wireless connection if you do not see one o'clock 🕐 below.  Checking prerequisites…

Using wget to manage downloads.

 🕛 > 🕧 Prerequisites: OK  Downloading TermuxArch…

setupTermuxArch. 100%[=======>]     153  --.-KB/s    in 0s
setupTermuxArch. 100%[=======>]  26.46K  --.-KB/s    in 0.01s

 🕛 > 🕐 TermuxArch download: OK

 🕛 > 🕜 TermuxArch v1.6 id0216 integrity: OK
head: cannot open '/proc/stat' for reading: Permission denied
archlinuxconfig.sh: line 257: t: unbound variable
setupTermuxArch.sh  v1.6 id0216: (Exit Signal 1) DONE 🏁

$

**Comment by sdrausty** [comment] 2018-08-29 15:10
@Root-voidX can you post output from `setupTermuxArch.sh sysinfo` once more.  I have modified it; And it gathers a little bit more diagnostic information regarding this issue and others now.

**Comment by sdrausty** [comment] 2018-08-29 15:44
@Root-voidX this https://github.com/sdrausty/TermuxArch/commit/7d56659b60fdb25107180622167d0fdec65d1b0d commit modifies:
```
if [[ ! "$(head /proc/stat 2>/dev/null)" ]] ; then
```
Which should let the script continue without thst peskey permission denied error.

**Comment by Root-voidX** [comment] 2018-08-30 05:43
@sdrausty

Here:

bash setupTermuxArch.sh sysinfo

Setting mode to sysinfo.

 🕛 > 🕛 setupTermuxArch v1.6 id0216 shall create a system information file.  Ensure background data is not restricted.  Run bash setupTermuxArch.sh help for additional information.  Check the wireless connection if you do not see one o'clock 🕐 below.  Checking prerequisites…

Using wget to manage downloads.

 🕛 > 🕧 Prerequisites: OK  Downloading TermuxArch…


Generating TermuxArch system information; Please wait…

 ✓ Generating: DONE

Begin TermuxArch system information.

`termux-info` results:

Updatable packages:
dropbear/stable 2018.76-3 aarch64 [upgradable from: 2017.75-2]
openssh/stable 7.8p1 aarch64 [upgradable from: 7.7p1]
System information:
Linux localhost 4.9.65-13734144 #1 SMP PREEMPT Tue Jun 19 23:39:30 KST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SM-G965W

Disk report 22299824 on /data Thu Aug 30 01:38:27 EDT 2018

BASH_VERSINFO[0] = 4
BASH_VERSINFO[1] = 4
BASH_VERSINFO[2] = 23
BASH_VERSINFO[3] = 1
BASH_VERSINFO[4] = release
BASH_VERSINFO[5] = aarch64-unknown-linux-android

cat /proc/cpuinfo results:

Processor       : AArch64 Processor rev 12 (aarch64)
processor       : 0
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp
CPU implementer : 0x51
CPU architecture: 8
CPU variant     : 0x7
CPU part        : 0x803
CPU revision    : 12

processor       : 1
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp
CPU implementer : 0x51
CPU architecture: 8
PU architecture: 8
CPU variant     : 0x7
CPU part        : 0x803
CPU revision    : 12

processor       : 2
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp
CPU implementer : 0x51
CPU architecture: 8
CPU variant     : 0x7
CPU part        : 0x803
CPU revision    : 12

processor       : 3
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp
CPU implementer : 0x51
CPU architecture: 8
CPU variant     : 0x7
CPU part        : 0x803
CPU revision    : 12

processor       : 4
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp
CPU implementer : 0x51
CPU architecture: 8
CPU variant     : 0x6
CPU part        : 0x802
CPU revision    : 13

processor       : 5
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp
CPU implementer : 0x51
CPU architecture: 8
CPU variant     : 0x6
CPU part        : 0x802
CPU revision    : 13

processor       : 6
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp
CPU implementer : 0x51
CPU architecture: 8
CPU variant     : 0x6
CPU part        : 0x802
CPU revision    : 13

processor       : 7
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp
CPU implementer : 0x51
CPU architecture: 8
CPU variant     : 0x6
CPU part        : 0x802
CPU revision    : 13

Hardware        : Qualcomm Technologies, Inc SDM845

dpkg --print-architecture result:

aarch64

getprop ro.product.cpu.abi result:

arm64-v8a

getprop ro.product.device result:

star2qltecs

Download directory information results.

/sdcard/Download exists
/storage/emulated/0/Download exists
~/downloads not found
/data/data/com.termux/files/home/storage/downloads exists

df /data/data/com.termux/files/home/arch results:

Filesystem      1K-blocks     Used Available Use% Mounted on
/dev/block/dm-3  54746384 32354404  22299820  60% /data

df results:

Filesystem                            1K-blocks     Used Available Use% Mounted on
tmpfs                                   2544192      796   2543396   1% /dev
/dev/block/dm-0                         4721044  3778676    942368  81% /system
/dev/block/dm-1                          720212   563352    156860  79% /vendor
/dev/block/dm-2                          355236   232808    122428  66% /odm
tmpfs                                   2546368        0   2546368   0% /mnt
tmpfs                                   2546368        0   2546368   0% /mnt/secure
/dev/block/bootdevice/by-name/cache      396744     8616    388128   3% /cache
/dev/block/bootdevice/by-name/persist     28144      620     27524   3% /persist
/dev/block/bootdevice/by-name/dsp         28144    14860     13284  53% /dsp
/dev/block/bootdevice/by-name/efs         16048      772     15276   5% /efs
/dev/block/bootdevice/by-name/apnhlos     97232    55744     41488  58% /firmware
/dev/block/bootdevice/by-name/modem      122816    80880     41936  66% /firmware-modem
/dev/block/bootdevice/by-name/omr         16048       12     16036   1% /omr
/dev/block/bootdevice/by-name/dqmdbg      12016       12     12004   1% /dqmdbg
/dev/block/dm-3                        54746384 32354404  22299820  60% /data
/data/knox/secure_fs/enc_user          54746384 32354404  22299820  60% /data/enc_user
/data/knox/secure_fs/enc_media         54746384 32354404  22299820  60% /data/knox/secure_fs/enc_media
tmpfs                                   2546368        0   2546368   0% /storage
/data/media                            54725904 32446564  2227934
/data/media                            54725904 32446564  22279340  60% /storage/emulated
/mnt/media_rw/9C33-6BBD               125533184 21884672 103648512  18% /storage/9C33-6BBD
tmpfs                                   2546368        0   2546368   0% /storage/self

du -hs /data/data/com.termux/files/home/arch results:

12K     /data/data/com.termux/files/home/arch

ls -al /data/data/com.termux/files/home/arch results:

total 12
drwx------ 3 u0_a290 u0_a290 4096 Aug 30 01:37 .
drwx------ 7 u0_a290 u0_a290 4096 Aug 30 01:37 ..
drwxrwxrwt 3 u0_a290 u0_a290 4096 Aug 30 01:38 tmp

uname -a results:

Linux localhost 4.9.65-13734144 #1 SMP PREEMPT Tue Jun 19 23:39:30 KST 2018 aarch64 Android

End `setupTermuxArchSysInfo5505.log` system information.

Share this information along with your issue at https://github.com/sdrausty/TermuxArch/issues; include input and output.  This file is found in `/data/data/com.termux/files/home/TermuxArch/setupTermuxArchSysInfo5505.log`.  If you think screenshots will help in a quicker resolution, include them in your post as well.

Submit this information if you plan to open up an issue at https://github.com/sdrausty/TermuxArch/issues to improve `setupTermuxArch.sh` along with a screenshot of the topic.  Include information about input and output.

setupTermuxArch.sh sysinfo v1.6 id0216: DONE 🏁

$

**Comment by sdrausty** [comment] 2018-08-30 10:59
@Root-voidX update to at least version v1.6 id1636 (current development version is gen.v1.6 id831221044952); this information was requested:
```
Device information results:

/dev/ashmem exists
/dev/ashmem is readable
/dev/shm does not exist
/dev/shm is not readable
/proc/stat exits
/proc/stat is readable
```
Also; is it working as intended?  https://github.com/michalbednarski contributed a review of our work https://github.com/termux/proot/issues/32#issuecomment-417057133 just hours ago, and important adjustments were made prior to this https://github.com/sdrausty/TermuxArch/commit/ccc578fe29d3dfd85477e0ebe2d261d2147476ab commit which may have resolved this issue.

**Comment by sdrausty** [comment] 2018-08-30 11:10
A new feature has just been added!  Express Refresh; use `setupTermuxArch.sh r` to access this enhancement.  It simple refreshes the files TermuxArch touches, and regenerates locales from this setting in Android.  A full system refresh is accomplished through `setupTermuxArch.sh re[fresh]` 🍀🌹

**Comment by sdrausty** [comment] 2018-08-30 11:19
@Root-voidX seeing how the Android 8 device looks in detail should help this issue as well; what is the output from `ls -al /dev/` and `ls -al /proc/`?

**Comment by sdrausty** [comment] 2018-08-30 11:53
> This is what i get after i refresh:

Try the `setupTermuxArch.sh bloom` option.  It's similar to working from the git repository, and it is much lighter 🐼☁🌀🌈

**Comment by sdrausty** [comment] 2018-08-30 12:10
> Try the setupTermuxArch.sh bloom option. It's similar to working from the git repository, and it is much lighter 🐼☁🌀🌈

It is designed to be run from Termux $HOME via `setupTermuxArch.sh bloom` 🌐 

> Use cd ~/TermuxArchBloom to continue.  Edit any of these files; Then use bash ./setupTermuxArch.sh [options] to run the files in ~/TermuxArchBloom.

Simply refresh TermuxArchBloom before beginning work.  The download is lighter.  There is no need for subsequent downloads when working from ~/TermuxArchBloom unless you want to update to the newest version.  To access the development release, change to `declare dfl="/gen" # Used for development` in setupTermuxArch.sh 🌈

**Comment by Root-voidX** [comment] 2018-08-30 18:31
@sdrausty

So i got a bit confused. Should I re git clone to update to latest comit and then run bloom?

**Comment by sdrausty** [comment] 2018-08-30 18:45
> So i got a bit confused. Should I re git clone to update to latest comit and then run bloom?

These two options (working in the repository and working in TermuxArchBloom) are completely independent from each other:
1) `git pull` in the TermuxArch repository.
2) `setupTermuxArch.sh bloom` which creates ~/TermuxArchBloom.

You can use any of these options **including simply running `setupTermuxArch.sh r`** for a quick refresh; `setupTermuxArch.sh` should update itself to the newest version automatically.

**Comment by sdrausty** [comment] 2018-08-31 14:12
@Root-voidX did `$ ./setupTermuxArch.sh r` work as intended on Android 8?

When you post output, please post output; Add you comments outside output.  Example:
Cannot access xLog; It says permission denied.
```
[10:00 arch ]$ l /dev/xLog
ls: cannot access '/dev/xLog': Permission denied
```
Or clearly comment:
```
[10:00 arch ]$ l /dev/xLog
ls: cannot access '/dev/xLog': Permission denied # Cannot access xLog; It says permission denied.
```
This should help us resolve this issue quicker.  

1) Post output from:
```
ls -al /dev
ls -al /dev/ashmem
head /dev/ashmem 
ls -al /dev/shm 
head /dev/shm 
ls -al /proc 
ls -al /proc/stat 
head /proc/stat 
```

2) Did `$ ./setupTermuxArch.sh r` work as intended on Android 8?

**Comment by Root-voidX** [comment] 2018-09-01 05:33
@sdrausty

Yes the new lightweight refresh works for me!!

Also 

$ ls -al /dev/
ls: cannot access '/dev/mobicore-user': Permission denied
ls: cannot access '/dev/wcd_dsp0_control': Permission denied
ls: cannot access '/dev/ramdump_wdsp': Permission denied
ls: cannot access '/dev/gpiochip31': Permission denied
ls: cannot access '/dev/ttyGS0': Permission denied
ls: cannot access '/dev/ccid_bulk': Permission denied
ls: cannot access '/dev/ccid_ctrl': Permission denied
ls: cannot access '/dev/dpl_ctrl': Permission denied
ls: cannot access '/dev/rmnet_ctrl': Permission denied
ls: cannot access '/dev/at_usb1': Permission denied
ls: cannot access '/dev/at_usb0': Permission denied
ls: cannot access '/dev/usb_ncm': Permission denied
ls: cannot access '/dev/usb_mtp_gadget': Permission denied
ls: cannot access '/dev/wwan_ioctl': Permission denied
ls: cannot access '/dev/ipa_tethering_bridge': Permission denied
ls: cannot access '/dev/ppp': Permission denied
ls: cannot access '/dev/seemplog': Permission denied
ls: cannot access '/dev/msm_sps': Permission denied
ls: cannot access '/dev/avtimer': Permission denied
ls: cannot access '/dev/wcd-dsp-glink': Permission denied
ls: cannot access '/dev/spcom': Permission denied
ls: cannot access '/dev/msm-rng': Permission denied
ls: cannot access '/dev/t-base-tui': Permission denied
ls: cannot access '/dev/msm_hdcp': Permission denied
ls: cannot access '/dev/qsee_ipc_irq_spss': Permission denied
ls: cannot access '/dev/iceufs': Permission denied
ls: cannot access '/dev/dcc_sram': Permission denied
ls: cannot access '/dev/console': Permission denied
ls: cannot access '/dev/sensors': Permission denied
ls: cannot access '/dev/smcinvoke': Permission denied
ls: cannot access '/dev/secdp_aux': Permission denied
ls: cannot access '/dev/pmsg0': Permission denied
ls: cannot access '/dev/qseecom': Permission denied
ls: cannot access '/dev/mobicore': Permission denied
ls: cannot access '/dev/sdp_mm': Permission denied
ls: cannot access '/dev/glink_pkt_loopback': Permission denied
ls: cannot access '/dev/smd11': Permission denied
ls: cannot access '/dev/apr_apps2': Permission denied
ls: cannot access '/dev/smd7': Permission denied
ls: cannot access '/dev/at_mdm0': Permission denied
ls: cannot access '/dev/glink_pkt_loopback_ctrl': Permission denied
ls: cannot access '/dev/smdcntl8': Permission denied
ls: cannot access '/dev/smd4': Permission denied
ls: cannot access '/dev/smd8': Permission denied
ls: cannot access '/dev/byte-cntr': Permission denied
ls: cannot access '/dev/msm_g711alaw': Permission denied
ls: cannot access '/dev/msm_aac': Permission denied
ls: cannot access '/dev/msm_amrwbplus': Permission denied
ls: cannot access '/dev/msm_aac_in': Permission denied
ls: cannot access '/dev/sdp_dlp': Permission denied
ls: cannot access '/dev/dek_evt': Permission denied
ls: cannot access '/dev/msm_amrwb_in': Permission denied
ls: cannot access '/dev/ccic_misc': Permission denied
ls: cannot access '/dev/msm_g711mlaw': Permission denied
ls: cannot access '/dev/msm_ape': Permission denied
ls: cannot access '/dev/loop-control': Permission denied
ls: cannot access '/dev/uhid': Permission denied
ls: cannot access '/dev/network_throughput': Permission denied
ls: cannot access '/dev/msm_wma': Permission denied
ls: cannot access '/dev/msm_amrwb': Permission denied
ls: cannot access '/dev/msm_hweffects': Permission denied
ls: cannot access '/dev/max_hrm': Permission denied
ls: cannot access '/dev/msm_wmapro': Permission denied
ls: cannot access '/dev/fuse': Permission denied
......keeps going

$ ls -al /dev/ashem
ls: cannot access '/dev/ashem': No such file or directory

$ head /dev/ashem
head: cannot open '/dev/ashem' for reading: No such file or directory
$

$ ls -al /dev/shem
ls: cannot access '/dev/shem': No such file or directory
$

$ head /dev/shem
head: cannot open '/dev/shem' for reading: No such file or directory
$

ls: cannot access '/proc/proc': No such file or directory
$ ls -al /proc/
ls: cannot access '/proc/fb': Permission denied
ls: cannot access '/proc/keys': Permission denied
ls: cannot access '/proc/kmsg': Permission denied
ls: cannot access '/proc/dplog': Permission denied
ls: cannot access '/proc/locks': Permission denied
ls: cannot access '/proc/stlog': Permission denied
ls: cannot access '/proc/swaps': Permission denied
ls: cannot access '/proc/crypto': Permission denied
ls: cannot access '/proc/nfclog': Permission denied
ls: cannot access '/proc/uh_log': Permission denied
ls: cannot access '/proc/uptime': Permission denied
ls: cannot access '/proc/usblog': Permission denied
ls: cannot access '/proc/vmstat': Permission denied
ls: cannot access '/proc/cgroups': Permission denied
ls: cannot access '/proc/cmdline': Permission denied
ls: cannot access '/proc/devices': Permission denied
ls: cannot access '/proc/ioports': Permission denied
ls: cannot access '/proc/iostats': Permission denied
ls: cannot access '/proc/loadavg': Permission denied
ls: cannot access '/proc/tsp_msg': Permission denied
ls: cannot access '/proc/version': Permission denied
ls: cannot access '/proc/consoles': Permission denied
ls: cannot access '/proc/kallsyms': Permission denied
ls: cannot access '/proc/slabinfo': Permission denied
ls: cannot access '/proc/boot_stat': Permission denied
ls: cannot access '/proc/buddyinfo': Permission denied
ls: cannot access '/proc/config.gz': Permission denied
ls: cannot access '/proc/dhd_trace': Permission denied
ls: cannot access '/proc/diskstats': Permission denied
ls: cannot access '/proc/key-users': Permission denied
ls: cannot access '/proc/last_kmsg': Permission denied
ls: cannot access '/proc/schedstat': Permission denied
ls: cannot access '/proc/iccc_ready': Permission denied
ls: cannot access '/proc/kpagecount': Permission denied
ls: cannot access '/proc/kpageflags': Permission denied
ls: cannot access '/proc/partitions': Permission denied
ls: cannot access '/proc/reset_klog': Permission denied
ls: cannot access '/proc/stlog_pipe': Permission denied
ls: cannot access '/proc/user_fault': Permission denied
ls: cannot access '/proc/execdomains': Permission denied
ls: cannot access '/proc/filesystems': Permission denied
ls: cannot access '/proc/reset_tzlog': Permission denied
ls: cannot access '/proc/sched_debug': Permission denied
ls: cannot access '/proc/vmallocinfo': Permission denied
ls: cannot access '/proc/pagetypeinfo': Permission denied
ls: cannot access '/proc/reset_reason': Permission denied
ls: cannot access '/proc/tsp_raw_data': Permission denied
ls: cannot access '/proc/reset_summary': Permission denied
ls: cannot access '/proc/stlog_version': Permission denied
ls: cannot access '/proc/store_lastkmsg': Permission denied
ls: cannot access '/proc/suspend_resume': Permission denied
ls: cannot access '/proc/tima_debug_log': Permission denied
total 0

$ ls -al /proc/stat
-r--r--r-- 1 root root 0 Sep  1 01:31 /proc/stat
$

$ head /proc/stat
head: cannot open '/proc/stat' for reading: Permission denied
$

**Comment by sdrausty** [comment] 2018-09-01 08:32
> Yes the new lightweight refresh works for me!!

Good news!  It looks like we are achieving the goal of this issue.  Can you `cat /proc/stat/*`, `cat /dev/ashmem` and `cat /dev/shm` from Arch please?

**Comment by Root-voidX** [comment] 2018-09-03 05:40
Okay @sdrausty

[01:28 home ]$ cat /proc/stat/*
cat: '/proc/stat/*': Not a directory
[01:31 home ]$ cat /proc/stat/
cat: /proc/stat/: Not a directory
[01:32 home ]$ cat /dev/ashem
cat: /dev/ashem: No such file or directory
[01:38 home ]$ cat /dev/shm
[01:39 home ]$ cat /dev/shm
[01:39 home ]$

**Comment by sdrausty** [comment] 2018-09-06 00:48
Good news!  I plan to get an Android 8 soon.  Which programs still do not work on Android 8, if any @Root-voidX?

**Closed** 2019-01-26 22:31 UTC
Labels: A26+, makepkg, shmem
