### ISSUE TITLE
Buffer is overwritten

### ISSUE THREAD

**Issue by he852100** [SDRausty/TermuxArch#201] opened 2019-12-15 18:19 UTC
The buffer is overwritten when docker is used(Occasional occurrence)

The problem was even worse when powershell was used

![Screenshot_20191216_014256](https://user-images.githubusercontent.com/26913892/70866918-5fc70000-1faa-11ea-9a40-a8c940852dd7.jpg)

[video](https://youtu.be/PdIrVbwYMhU)

**Comment by SDRausty** [comment] 2019-12-15 20:16
@he852100 this might be caused by [`PS1="[\[\e[38;5;148m\]\u\[\e[1;0m\]\A\[\e[1;38;5;112m\]\W\[\e[0m\]]$ "`](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash#L59) in [`archlinuxconfig.bash`](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash) after it writes the .bashrc file.  To test, comment this line out in the `.bashrc` file, and see if the problem continues.

On the other hand, the origin of this buffer issue [might be here in termux-packages](https://github.com/termux/termux-packages/issues?&q=is%3Aissue+buffer+over) and [also here at termux-app](https://github.com/termux/termux-packages/issues?&q=is%3Aissue+buffer+over).

> when docker is used

Can you outline the steps that you used to install docker?

**Comment by he852100** [comment] 2019-12-16 01:48
>when docker is used

It could be my mischaracterization

> might be here in termux-packages

They asked me to come to you.Say it's nothing to do with them

I tried to use the package other ones and also encountered the same problem

<https://wiki.termux.com/wiki/Fedora>

**Comment by SDRausty** [comment] 2019-12-16 01:50
> To test, comment this line out in the .bashrc file, and see if the problem continues.

**Comment by he852100** [comment] 2019-12-16 02:20
The problem is still there

I deleted bash_profile and bashrc.

**Comment by he852100** [comment] 2019-12-16 12:56
@SDRausty I want to make sure whose problem is.

If it's a software problem, I'll go find them

**Comment by SDRausty** [comment] 2019-12-24 03:15
From https://github.com/termux/termux-app/pull/1390 terminal emulator: clear scrollback buffer when resetting to initial state #1390

> RIS sequence (sent by reset utility) does a lot more things like resetting terminal parameters and clearing memory including scrollback buffer and in some implementations even clipboard.

@he852100 this merged pull request might be a solution for this issue.

**Comment by he852100** [comment] 2019-12-26 11:51
@SDRausty thanks.

<https://github.com/PowerShell/PSReadLine/issues/1269>

**Comment by SDRausty** [comment] 2019-12-28 15:22
@he852100 you are welcome 🔩 :)

**Closed** 2019-12-30 16:09 UTC

**Comment by SDRausty** [comment] 2022-03-18 17:07
>overwritten when docker is used

[`udocker` is available;  A basic user tool to execute simple docker containers in batch or interactive systems without root privileges.](https://github.com/indigo-dc/udocker)
