### ISSUE TITLE
Error running fakeroot

### ISSUE THREAD

**Issue by HitaloKun** [SDRausty/TermuxArch#208] opened 2020-01-23 14:55 UTC
**I'm trying to compile yay but I get an error referring to fakeroot using makepkg**

![](https://i.imgur.com/83T5N4S.jpg)

**Comment by alissonlauffer** [comment] 2020-01-25 05:51
Duplicate of #26

**Closed** 2020-01-25 11:52 UTC

**Comment by HitaloKun** [comment] 2020-01-25 11:53
Problem solved, fakeroot work from and yay installed.

**Comment by johndoehack** [comment] 2020-02-03 23:57
got error 416 when self configufing mirrors
